/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.53
 * Generated at: 2014-04-11 09:51:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class addgroup_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0 Transitional//EN\">\n");
      out.write("<HTML><HEAD><TITLE>AddGroup</TITLE>\n");
      out.write("<META http-equiv=Content-Language content=zh-cn>\n");
      out.write("<META http-equiv=Content-Type content=\"text/html; charset=gb2312\">\n");
      out.write("<META content=\"MSHTML 6.00.2800.1611\" name=GENERATOR>\n");
      out.write("</HEAD>\n");
      out.write("<BODY bgColor=#eef8e0 leftMargin=0 topMargin=0 MARGINWIDTH=\"0\" MARGINHEIGHT=\"0\">\n");
      out.write("<FORM name=groupAdd action=addGroup method=post>\n");
      out.write("<TABLE cellSpacing=0 cellPadding=0 width=1004 border=0>\n");
      out.write("  <TBODY>    \n");
      out.write("    \n");
      out.write("  <TR>\n");
      out.write("    \n");
      out.write("    <TD background=../images/crm_12.gif colSpan=6>\n");
      out.write("      <TABLE id=table1 cellSpacing=0 cellPadding=0 width=\"98%\" border=0>\n");
      out.write("        <TBODY>\n");
      out.write("        <TR>\n");
      out.write("          <TD>\n");
      out.write("            <TABLE id=table2 cellSpacing=1 cellPadding=0 width=\"100%\" \n");
      out.write("              border=0>\n");
      out.write("              <TBODY>\n");
      out.write("              <TR>\n");
      out.write("                <TD align=middle width=81><FONT color=#000000>GroupName:</FONT></TD>\n");
      out.write("                <TD><INPUT title=groupname maxLength=16 size=16 \n");
      out.write("                   name=groupname></TD>\n");
      out.write("              \t</TD>\n");
      out.write("              </TR>\n");
      out.write("              <TR>                \n");
      out.write("                <TD><INPUT title= maxLength=16 size=16 \n");
      out.write("                  value=add name=groupname type=\"submit\">\n");
      out.write("              \t</TD>\n");
      out.write("              \t<TD><INPUT title= maxLength=16 size=16 \n");
      out.write("                  value=cancel name=nothing type=\"reset\">\n");
      out.write("              \t</TD>\n");
      out.write("              </TR>\n");
      out.write("              </TBODY>\n");
      out.write("             </TABLE>\n");
      out.write("          </TD>\n");
      out.write("        </TR>\n");
      out.write("        </TBODY>\n");
      out.write("       </TABLE>\n");
      out.write("   \t</TD>\n");
      out.write("    </TR>\n");
      out.write("    </TBODY>\n");
      out.write("    </TABLE>\n");
      out.write("   </FORM>\n");
      out.write("  </BODY>\n");
      out.write("</HTML>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
